### ISSUE TITLE
errors with python3

### ISSUE THREAD

**Issue by cfregly** [guildai/_guild-python-legacy#2]
```
Traceback (most recent call last):
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/system.py", line 51, in _read_gpu_attrs
    raw = subprocess.check_output(guild.app.script("gpu-attrs"))
  File "/Users/cfregly/miniconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/cfregly/miniconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/Users/cfregly/workspace-fluxcapacitor/guild-python/scripts/gpu-attrs' returned non-zero exit status 127.
INFO: [guild] nvidia-smi not installed, cannot collect GPU stats (see https://developer.nvidia.com/cuda-downloads)
  File "./intro.py", line 118
    print "Step %i: %s=%f" % (step, name, accuracy_val)
                         ^
SyntaxError: invalid syntax
Process Process-2:
Traceback (most recent call last):
  File "/Users/cfregly/miniconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/cfregly/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/tasks/log_system_attrs.py", line 8, in start
    _tensorflow_attrs())
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/tasks/log_system_attrs.py", line 22, in _tensorflow_attrs
    return list(guild.tensorflow_support.tf_attrs().items())
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/tensorflow_support.py", line 9, in tf_attrs
    _ensure_tf_attrs()
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/tensorflow_support.py", line 15, in _ensure_tf_attrs
    _tf_attrs = _read_tf_attrs()
  File "/Users/cfregly/workspace-fluxcapacitor/guild-python/guild/tensorflow_support.py", line 25, in _read_tf_attrs
    return _parse_tf_attrs(raw.encode("UTF-8"))
AttributeError: 'bytes' object has no attribute 'encode'
```

**Comment by gar1t** [comment]
Unfortunately the new build scheme, where we're resolving dependencies explicitly at buildtime (much better runtime experience!) makes Python 3 support even more challenging. I'll open a general "Python 3" issue so that we can track status, but I'll close this one as it's a bit low level (and is "fixed" anyway, not that it matters given the real issues now lie with how we're managing dependencies).
