### ISSUE TITLE
Cannot build within Docker

### ISSUE THREAD

**Issue by cfregly** [guildai/_guild-python-legacy#5]
otherwise, you'll see this:
```
cp: cannot stat 'external/org_psutil/psutil/_psutil_linux.so': No such file or directory
Target //guild:guild failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 659.485s, Critical Path: 239.24s
FAILED: Build did NOT complete successfully
```

**Comment by cfregly** [comment]
actually, even with `pip install psutil`, i'm seeing the following:

```
ERROR: /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/org_psutil/BUILD.bazel:10:1: Executing genrule @org_psutil//:psutil_native failed (Exit 1)

cp: cannot stat 'external/org_psutil/psutil/_psutil_linux.so': No such file or directory

/root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/bazel-sandbox/6458286971582026557/execroot/ai_guild_guild/external/org_psutil 

/root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/bazel-sandbox/6458286971582026557/execroot/ai_guild_guild
running build_ext
building 'psutil._psutil_linux' extension
creating build
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/psutil
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=522 -DPSUTIL_LINUX=1 -I/opt/conda/include/python3.6m -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_linux.o
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/psutil
gcc -pthread -shared -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib,--no-as-needed build/temp.linux-x86_64-3.6/psutil/_psutil_linux.o -L/opt/conda/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/psutil/_psutil_linux.cpython-36m-x86_64-linux-gnu.so
building 'psutil._psutil_posix' extension
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DPSUTIL_POSIX=1 -DPSUTIL_VERSION=522 -DPSUTIL_LINUX=1 -I/opt/conda/include/python3.6m -c psutil/_psutil_posix.c -o build/temp.linux-x86_64-3.6/psutil/_psutil_posix.o
gcc -pthread -shared -L/opt/conda/lib -Wl,-rpath=/opt/conda/lib,--no-as-needed build/temp.linux-x86_64-3.6/psutil/_psutil_posix.o -L/opt/conda/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/psutil/_psutil_posix.cpython-36m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.6/psutil/_psutil_linux.cpython-36m-x86_64-linux-gnu.so -> psutil
copying build/lib.linux-x86_64-3.6/psutil/_psutil_posix.cpython-36m-x86_64-linux-gnu.so -> psutil
/root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/bazel-sandbox/6458286971582026557/execroot/ai_guild_guild
Target //guild:guild failed to build

Use --verbose_failures to see the command lines of failed build steps.

INFO: Elapsed time: 480.801s, Critical Path: 94.97s

FAILED: Build did NOT complete successfully
```

**Comment by cfregly** [comment]
might be a python 3 thing... hmm.

**Comment by cfregly** [comment]
INFO: Analysed target //guild:guild (270 packages loaded).
INFO: Found 1 target...
[0 / 3] BazelWorkspaceStatusAction stable-status.txt
[36 / 165] Compiling external/protobuf/src/google/protobuf/message.cc [for host]; 2s processwrapper-sandbox ... (3 actions running)
[52 / 165] Compiling external/protobuf/src/google/protobuf/descriptor.cc [for host]; 7s processwrapper-sandbox ... (3 actions running)
[74 / 165] Compiling external/protobuf/src/google/protobuf/text_format.cc [for host]; 2s processwrapper-sandbox ... (4 actions running)
[79 / 165] Compiling external/protobuf/src/google/protobuf/compiler/csharp/csharp_message.cc [for host]; 12s processwrapper-sandbox ... (4 actions running)
[113 / 165] Compiling external/protobuf/src/google/protobuf/compiler/cpp/cpp_field.cc [for host]; 1s processwrapper-sandbox ... (4 actions running)
[155 / 165] Compiling external/protobuf/src/google/protobuf/compiler/java/java_message_lite.cc [for host]; 1s processwrapper-sandbox ... (3 actions running)
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/profile/trace_events_pb2.py:
external/protobuf/python: warning: directory does not exist.
[717 / 868] Compiling 4 TypeScript files @org_tensorflow_tensorboard//tensorboard/components/tf_globals:tf_globals; 5s processwrapper-sandbox ... (4 actions running)
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/histogram/plugin_data_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/protobuf/python/google/protobuf/any_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/scalar/plugin_data_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/projector/projector_config_pb2.py:
external/protobuf/python: warning: directory does not exist.
[767 / 937] Compiling 25 TypeScript files @org_tensorflow_tensorboard//tensorboard/plugins/graph/tf_graph_common:tf_graph_common; 14s processwrapper-sandbox ... (4 actions running)
[1,040 / 1,267] Compiling 25 TypeScript files @org_tensorflow_tensorboard//tensorboard/plugins/graph/tf_graph_common:tf_graph_common; 49s processwrapper-sandbox ... (4 actions running)
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/audio/plugin_data_pb2.py:
external/protobuf/python: warning: directory does not exist.
INFO: From ProtoCompile external/org_tensorflow_tensorboard/tensorboard/plugins/image/plugin_data_pb2.py:
external/protobuf/python: warning: directory does not exist.
ERROR: /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/org_psutil/BUILD.bazel:10:1: Executing genrule @org_psutil//:psutil_native failed (Exit 1)
cp: cannot stat 'external/org_psutil/psutil/_psutil_linux.so': No such file or directory

**Comment by cfregly** [comment]
switched to python 2.7.10 and things got further, but still no dice:

```
Target //guild:guild up-to-date:
  bazel-bin/guild/guild
INFO: Elapsed time: 371.936s, Critical Path: 184.93s
INFO: Build completed successfully, 1277 total actions
stty: 'standard input': Inappropriate ioctl for device
Traceback (most recent call last):
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/main.py", line 53, in <module>
    main()
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/main.py", line 27, in main
    guild.view_cmd,
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cli.py", line 55, in main
    p = parser(commands)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cli.py", line 45, in parser
    _add_command(cmd, sub_p)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cli.py", line 52, in _add_command
    module.add_parser(subparsers)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/prepare_cmd.py", line 14, in add_parser
    """)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cmd_support.py", line 19, in add_parser
    description=_format_description(description))
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cmd_support.py", line 23, in _format_description
    return "\n\n".join([_format_par(par) for par in pars])
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cmd_support.py", line 28, in _format_par
    width=_safe_console_width() - 10)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cmd_support.py", line 36, in _safe_console_width
    return max(_console_width(), 72)
  File "/root/guild-python/bazel-bin/guild/guild.runfiles/org_guildai_guild/guild/cmd_support.py", line 41, in _console_width
    _, cols = os.popen('stty size', 'r').read().split()
ValueError: need more than 0 values to unpack
The command '/bin/sh -c git clone https://github.com/guildai/guild-python.git   && cd guild-python   && bazel build guild   && bazel-bin/guild/guild check   && bazel-bin/guild/guild check --all-tests' returned a non-zero code: 1
```

**Comment by cfregly** [comment]
note:  i'm running this inside Docker.

here's the relevant part of the Dockerfile:

https://github.com/fluxcapacitor/pipeline/commit/6619caea9012d270ef8b4913abe12e7e3626ba8d#diff-3ab340a2ac5eb5d754e842750f537320

**Comment by cfregly** [comment]
```
ERROR: /root/guild-python/components/BUILD:6:1: Vulcanizing /guild.html failed (Exit 1)
2017-09-04 01:43:32.512 WARNING /app-layout/app-drawer/app-drawer.html.js:116: WARNING - Function Node.prototype.removeEventListener: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
        document.removeEventListener('keydown', this._boundEscKeydownHandler);
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.561 WARNING /app-layout/app-drawer/app-drawer.html.js:393: WARNING - Function Node.prototype.addEventListener: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
            document.addEventListener('keydown', this._boundEscKeydownHandler);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.561 WARNING /app-layout/app-drawer/app-drawer.html.js:396: WARNING - Function Node.prototype.removeEventListener: called with 2 argument(s). Function requires at least 3 argument(s) and no more than 3 argument(s).
            document.removeEventListener('keydown', this._boundEscKeydownHandler);
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.561 WARNING /fa-awesome/fa-awesome.html.js:19: WARNING - Bad type annotation. Unknown type bool
       * @type bool
               ^

2017-09-04 01:43:32.562 WARNING /guild-components-page/guild-components-page.html.js:28: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.562 WARNING /guild-components-page/guild-components-page.html.js:33: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.563 WARNING /guild-components-page/guild-components-page.html.js:38: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.564 WARNING /guild-components-page/guild-components-page.html.js:86: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.565 WARNING /guild-components-page/guild-components-page.html.js:98: WARNING - cannot instantiate non-constructor
       util: new function() {
             ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.565 WARNING /guild-data/guild-data-listener.html.js:64: WARNING - actual parameter 1 of Window.clearTimeout does not match formal parameter
found   : Object
required: (null|number|undefined)
             window.clearTimeout(this.pendingFetch);
                                 ^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.566 WARNING /guild-data/guild-data-listener.html.js:65: WARNING - assignment to property pendingFetch of GuildDataListenerElement
found   : null
required: Object
             this.pendingFetch = null;
             ^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.567 WARNING /guild-data/guild-data-listener.html.js:65: WARNING - assignment to property pendingFetch of GuildRunDataListenerElement
found   : null
required: Object
             this.pendingFetch = null;
             ^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.568 WARNING /guild-datatable/guild-datatable.html.js:41: WARNING - Property getContentChildNodes never defined on GuildDatatableElement
           var cols = this.getContentChildNodes("[select=datatable-col]");
                           ^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.568 WARNING /guild-datatable/guild-datatable.html.js:48: WARNING - assignment to property searchInput of GuildDatatableElement
found   : (Element|null)
required: Object
           this.searchInput = this.$$("input[type='search']");
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.569 WARNING /guild-datatable/guild-datatable.js:18: WARNING - cannot instantiate non-constructor
Guild.DataTable = new function() {
                  ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.570 WARNING /guild-env/guild-env.html.js:40: WARNING - cannot instantiate non-constructor
       util: new function() {
             ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.570 WARNING /guild-fields/guild-fields.html.js:30: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.571 WARNING /guild-line-chart/guild-line-chart.html.js:48: WARNING - assignment to property instance of GuildLineChartElement
found   : (Element|null)
required: Object
           this.instance = this.stamp();
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.571 WARNING /guild-project/project.js:18: WARNING - cannot instantiate non-constructor
Guild.Project = new function() {
                ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.572 WARNING /guild-run-select/guild-run-select-item.html.js:22: WARNING - Property Run never defined on Guild
           return Guild.Run.runLabel(run);
                        ^^^

2017-09-04 01:43:32.572 WARNING /guild-run-select/guild-run-select-item.html.js:26: WARNING - Property Run never defined on Guild
           return Guild.Run.runStatus(run);
                        ^^^

2017-09-04 01:43:32.573 WARNING /guild-run-status/guild-run-status.html.js:14: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.573 WARNING /guild-run-status/guild-run-status.html.js:15: WARNING - Property Run never defined on Guild
           return run ? Guild.Run.runStatus(run) : {};
                              ^^^

2017-09-04 01:43:32.573 WARNING /guild-run/guild-run-data-listener.html.js:84: WARNING - cannot instantiate non-constructor
       util: new function() {
             ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.574 WARNING /guild-series/guild-series.html.js:30: WARNING - Property Run never defined on Guild
           var run = Guild.Run.runForId(selected, runs);
                           ^^^

2017-09-04 01:43:32.574 WARNING /guild-series/guild-series.html.js:43: WARNING - cannot instantiate non-constructor
       util: new function() {
             ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.575 WARNING /guild-view/guild-view-app-layout.html.js:25: WARNING - Property getContentChildNodes never defined on GuildViewAppLayoutElement
           this.pages = this.getContentChildNodes("[select='guild-view-page']");
                             ^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.575 WARNING /guild-view/guild-view-app-layout.html.js:82: WARNING - cannot instantiate non-constructor
       util: new function() {
             ^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.576 WARNING /guild-view/guild-view-page.html.js:39: WARNING - assignment to property instance of GuildViewPageElement
found   : (Element|null)
required: Object
           this.instance = this.stamp();
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.990 SEVERE /guild-data/data.js:15:
Originally at:
/guild-data/data.ts:16: ERROR - Variable guild first declared in /guild-util/util.js

2017-09-04 01:43:32.991 SEVERE /guild-datatable/guild-datatable.js:16: ERROR - Variable Guild first declared in /guild-data/guild-data-listener.html.js
var Guild = Guild || {};
    ^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.992 SEVERE /guild-datatable/guild-datatable.js:23: ERROR - variable jQuery is undeclared
        return jQuery(table).DataTable({
               ^^^^^^

2017-09-04 01:43:32.992 SEVERE /guild-project/project.js:16: ERROR - Variable Guild first declared in /guild-data/guild-data-listener.html.js
var Guild = Guild || {};
    ^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:32.994 SEVERE /guild-run/run.js:15:
Originally at:
/guild-run/run.ts:16: ERROR - Variable guild first declared in /guild-util/util.js

2017-09-04 01:43:32.996 SEVERE /guild-util/reduce.js:15:
Originally at:
/guild-util/reduce.ts:16: ERROR - Variable guild first declared in /guild-util/util.js

2017-09-04 01:43:32.997 SEVERE /guild-util/util.js:42:
Originally at:
/guild-util/util.ts:39: ERROR - variable numeral is undeclared

2017-09-04 01:43:33.000 SEVERE /guild-view/guild-fullscreen-behavior.html.js:2: ERROR - Variable Guild first declared in /guild-data/guild-data-listener.html.js
 var Guild = Guild || {};
     ^^^^^^^^^^^^^^^^^^^

2017-09-04 01:43:33.000 WARNING 8 error(s), 29 warning(s), 66.4% typed
Target //guild:guild failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 247.679s, Critical Path: 162.31s
FAILED: Build did NOT complete successfully
```
