### ISSUE TITLE
guild-lite not building properly

### ISSUE THREAD

**Issue by cfregly** [guildai/_guild-python-legacy#7]
```
git clone https://github.com/guildai/guild-python.git
cd guild-python 
bazel build guild:guild-lite 
```

```
[915 / 944] Compiling 25 TypeScript files @org_tensorflow_tensorboard//tensorboard/plugins/graph/tf_graph_common:tf_graph_common; 107s processwrapper-sandbox ... (4 actions running)
[926 / 944] Compiling 25 TypeScript files @org_tensorflow_tensorboard//tensorboard/plugins/graph/tf_graph_common:tf_graph_common; 136s processwrapper-sandbox ... (2 actions running)
[926 / 944] Compiling 25 TypeScript files @org_tensorflow_tensorboard//tensorboard/plugins/graph/tf_graph_common:tf_graph_common; 169s processwrapper-sandbox ... (2 actions running)
[941 / 944] Vulcanizing /tensorboard.html; 19s processwrapper-sandbox
INFO: From Vulcanizing /tensorboard.html:
2017-09-05 23:15:10.017 WARNING /tf-graph-info/tf-graph-icon.html.js:11: WARNING - Bad type annotation. Unknown type tf.graph.Node
           * @type {tf.graph.Node}
                    ^

2017-09-05 23:15:10.038 WARNING /tf-graph-info/tf-graph-icon.html.js:22: WARNING - Bad type annotation. Unknown type tf.graph.render.RenderNodeInfo
           * @type {tf.graph.render.RenderNodeInfo}
                    ^

2017-09-05 23:15:10.038 WARNING /tf-graph-info/tf-node-list-item.html.js:9: WARNING - Bad type annotation. Unknown type tf.graph.Node
           * @type {tf.graph.Node}
                    ^

2017-09-05 23:15:10.039 WARNING /tf-graph-info/tf-node-list-item.html.js:14: WARNING - Bad type annotation. Unknown type tf.graph.Node
           * @type {tf.graph.Node}
                    ^

2017-09-05 23:15:10.040 WARNING /tf-graph-op-compat-card/tf-graph-op-compat-list-item.html.js:9: WARNING - Bad type annotation. Unknown type tf.graph.Node
       * @type {tf.graph.Node}
                ^

2017-09-05 23:15:10.040 WARNING /tf-graph-op-compat-card/tf-graph-op-compat-list-item.html.js:14: WARNING - Bad type annotation. Unknown type tf.graph.Node
       * @type {tf.graph.Node}
                ^

2017-09-05 23:15:10.041 WARNING /tf-graph/tf-graph-scene.html.js:20: WARNING - Bad type annotation. Unknown type d3_zoom
    /** @type {d3_zoom} d3 zoom object */
               ^

2017-09-05 23:15:10.041 WARNING /tf-graph/tf-graph-scene.html.js:60: WARNING - Bad type annotation. Unknown type d3.scale.ordinal
     * @type {d3.scale.ordinal}
              ^

2017-09-05 23:15:10.042 WARNING /tf-graph/tf-graph-scene.html.js:67: WARNING - Bad type annotation. Unknown type tf.scene.Minimap
     * @type {tf.scene.Minimap}
              ^

2017-09-05 23:15:10.042 WARNING 0 error(s), 9 warning(s), 63.1% typed
Target //guild:guild-lite up-to-date:
  bazel-bin/guild/guild-lite
INFO: Elapsed time: 295.657s, Critical Path: 209.56s
INFO: Build completed successfully, 944 total actions
stty: 'standard input': Inappropriate ioctl for device
Traceback (most recent call last):
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/main_lite.py", line 22, in <module>
    guild.train_cmd,
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/main_impl.py", line 10, in main
    guild.cli.main(cmds)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cli.py", line 55, in main
    p = parser(commands)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cli.py", line 45, in parser
    _add_command(cmd, sub_p)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cli.py", line 52, in _add_command
    module.add_parser(subparsers)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/prepare_cmd.py", line 14, in add_parser
    """)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cmd_support.py", line 19, in add_parser
    description=_format_description(description))
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cmd_support.py", line 23, in _format_description
    return "\n\n".join([_format_par(par) for par in pars])
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cmd_support.py", line 28, in _format_par
    width=_safe_console_width() - 10)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cmd_support.py", line 36, in _safe_console_width
    return max(_console_width(), 72)
  File "/root/guild-python/bazel-bin/guild/guild-lite.runfiles/org_guildai_guild/guild/cmd_support.py", line 41, in _console_width
    _, cols = os.popen('stty size', 'r').read().split()
ValueError: need more than 0 values to unpack
The command '/bin/sh -c git clone https://github.com/guildai/guild-python.git   && cd guild-python   && bazel build guild:guild-lite   && bazel-bin/guild/guild-lite check --all-tests' returned a non-zero code: 1
```

**Comment by cfregly** [comment]
Here's the relevant Dockerfile: 
 https://github.com/fluxcapacitor/pipeline/blob/master/predict/Dockerfile#L266

**Comment by gar1t** [comment]
I committed a fix in ad5e977.
