### ISSUE TITLE
Python 2.7 Error:  TypeError: decode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by cfregly** [guildai/_guild-python-legacy#9]
```
Traceback (most recent call last):
  File "/root/guild-python/bazel-bin/guild/guild", line 46, in <module>
guild_version:          GIT (e1e9ea0)
guild_home:             /root/guild-python
python_version:         2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:04:42) [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
    main()
  File "/root/guild-python/bazel-bin/guild/guild", line 14, in main
    guild.main.main()
  File "/root/guild-python/guild/main.py", line 27, in main
    guild.view_cmd,
  File "/root/guild-python/guild/cli.py", line 67, in main
    _handle_args(args)
  File "/root/guild-python/guild/cli.py", line 101, in _handle_args
    args.func(args)
  File "/root/guild-python/guild/check_cmd.py", line 37, in main
    _print_info(args)
  File "/root/guild-python/guild/check_cmd.py", line 57, in _print_info
    _print_tensorflow_info(args.verbose)
  File "/root/guild-python/guild/check_cmd.py", line 75, in _print_tensorflow_info
    _print_check_results("tensorflow-check", verbose)
  File "/root/guild-python/guild/check_cmd.py", line 84, in _print_check_results
    sys.stdout.write(out.decode(sys.stdout.encoding))
TypeError: decode() argument 1 must be string, not None
```

**Comment by cfregly** [comment]
i have this issue with when i switch to python 3:

```
ERROR: /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/org_psutil/BUILD.bazel:10:1: declared output 'external/org_psutil/psutil/_psutil_linux.cpython-35m-x86_64-linux-gnu.so' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/org_psutil/BUILD.bazel:10:1: declared output 'external/org_psutil/psutil/_psutil_posix.cpython-35m-x86_64-linux-gnu.so' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely)
ERROR: /root/.cache/bazel/_bazel_root/cc96cea90b54a4936c65c34f3306c63b/external/org_psutil/BUILD.bazel:10:1: not all outputs were created or valid
Target //guild:guild failed to build
```
